---

- name: Configuration for local Jekyll development on Vagrant VM
  hosts: all
  become: yes
  vars:
    user_name: "vagrant"

  roles:
    - common
#    - nodejs
    - { role: rvm_io.rvm1-ruby, tags: ruby }
    - jekyll
